#!/usr/bin/env bash
# This script pings an IP address passed as an argument.

# Requirements:
#
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times

if [ $# -lt 1 ]; then
echo “Usage: 5-is_the_host_on_the_network {IP_ADDRESS}”
else
ping -c 5 “$@“
fi


