#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# Bash script must be 5 lines long or less

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
